### ISSUE TITLE
Fork for this unmaintained repository

### ISSUE THREAD

**Issue by delete** [dpopescu/ts-serializer#13]
This project is really awesome but it seems it is not maintained anymore, so , I created a fork with some modifications. 

https://github.com/delete/ts-serializer

Maybe this fork can help someone else.

**Comment by dpopescu** [comment]
Sorry for this guys. I was really busy lately. You can create a PR and merge whatever you made. I can even add you as a contributor. If we can manage to get enough people on-board we can update this regularly.
