### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by Tridecagon** [dpopescu/ts-serializer#16]
The published package does not appear to be valid JS. The codesandbox example given in the readme currently exhibits this issue.

https://codesandbox.io/s/ts-serializer-playground-gdbid

**Comment by delete** [comment]
Yeah, the build seems to be broken. I'll take a look at this! 
Thanks for reporting and sorry for the trouble.

**Comment by dpopescu** [comment]
@Tridecagon the issue was merged into master and a new version was uploaded to NPM Registry. V2.2.4. Thanks for reporting this.
