### ISSUE TITLE
Issue when using with Nest.js -  ReferenceError: window is not defined

### ISSUE THREAD

**Issue by vijayakumar-psg587** [dpopescu/ts-serializer#20]
Hi,

First of all, I would like to express my regards as to the development this module. Great one with decorators. One of the best out there for serialization and deserialization.  Helps in mitigating a  lot of unnecessary boiler plate code.

Now, I would like to report an issue which did not exist in the prev version - 1.0.1
There seems to be a reference error when used in nodejs/nestjs
Node -version -  12.3.0
Nestjs -version - 6.4.2

This is the error
```
/node_modules/ts-serializer/dist/webpack:/TSerializer/webpack/universalModuleDefinition:10
})(window, function() {
 ^
ReferenceError: window is not defined
    at Object.<anonymous> (/mnt/sda7/personal/Nest/feedback-project-nest-6-2-2020/node_modules/ts-serializer/dist/webpack:/TSerializer/webpack/universalModuleDefinition:10:2)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
```
It would be great if a check for window object is made and if it doesnt probably revert to the "module" property I suppose?

**Comment by delete** [comment]
Hi @vijayakumar-psg587, thanks, and thanks for your report.

I did reproduce this behavior in a [codesanbox](https://codesandbox.io/s/bug-nestjs-tsserializer-m1z2h). It's seems that we are building only to web.

I will take a look asap.

**Comment by debasisdev** [comment]
Hi @delete, thanks for your feedback - We are using it as a dependency in our Apollo GraphQL based Server Side Application. If we update to the latest version `2.2.4` we're getting the same `ReferenceError: window is not defined` error. Instead we used `1.0.1` and it seems to work pretty fine. But we would like to upgrade to the new features that're not limited to only web :)

**Comment by debasisdev** [comment]
I have fixed the Issue @delete - If you want I can create a PR given you give me the correct access rights (permission) as a contributor. Thanks

**Comment by tleclaire** [comment]
I would like to have this fixed as well. @debasisdev can you provide the fix until this has been merged into the repo?

**Comment by debasisdev** [comment]
The quickest and easy-fix is to have it in Webpack 4 config as it's changed internally.
`const path = require('path');

module.exports = {
	entry: __dirname + '/ts-serializer',
	mode: 'production',
	devtool: 'inline-source-map',
	resolve: {
		extensions: [ '.tsx', '.ts', '.js' ]
	  },
	output:{
		globalObject: "this",
		path: path.join(__dirname, 'dist'),
		publicPath: '/',
		filename: 'ts-serializer.js',
		libraryTarget: 'umd',
		library: 'TSerializer'
	},
	module: {
		rules: [
			{
			  test: /\.tsx?$/,
			  use: 'ts-loader',
			  exclude: /node_modules/
			}
		  ]
	}
};`

The change here is the line `globalObject: "this"`

**Comment by debasisdev** [comment]
People who want to use v2.2.4 in their Server-side Code, can add an Empty Global Window which is more of a hack than a fix 😢

**Comment by delete** [comment]
Thanks @debasisdev ! You can fork the repository and open a pull request against this repository. Will more than appreciated.

**Comment by debasisdev** [comment]
@delete As suggested, I created a PR #21 to resolve this issue. Release Version is bumped too to `2.2.5`. 😃

**Comment by debasisdev** [comment]
@delete Please publish the changes to npm with version `2.2.5` :)

**Comment by vijayakumar-psg587** [comment]
@debasisdev @delete thanks for fixing it quickly. Eagerly awaiting for the new version :)

**Comment by debasisdev** [comment]
@delete @dpopescu Could you check the release in npm? The package only contains 3 files, namely, README, Package.json., and LICENSE. No `dist`or binaries found. Please recheck the publish step :smile . Thanks

**Comment by debasisdev** [comment]
As reported #22

**Comment by Agranom** [comment]
@delete pls republish the lib, 2.2.5 is broken now

**Comment by delete** [comment]
Only @dpopescu has access to publish to NPM, sorry the delay guys.

**Comment by dpopescu** [comment]
Terribly sorry for the delay guys. I will publish the lib tonight. 22:00 GMT. I really need to add a rule to my inbox to get all notifications from Github. Sorry again.

**Comment by dpopescu** [comment]
Done. New version is 2.2.6.
