### ISSUE TITLE
Version 2.2.5 broken

### ISSUE THREAD

**Issue by LanderN** [dpopescu/ts-serializer#22]
Installing version 2.2.5 via npm seems to be broken.
`node_modules/ts-serializer` only contains the following files:
- LICENSE
- package.json
- README.md

For now, I rolled back to 2.2.4. This version does have a `dist` folder with the required files.

**Comment by delete** [comment]
@dpopescu can you take a look at this, please?

**Comment by dpopescu** [comment]
Version 2.2.6 works now.
